name: PyFoundations
channels:
  - defaults
dependencies:
  - backcall=0.1.0
  - ca-certificates=2019.1.23=0
  - certifi=2018.11.29
  - colorama=0.4.1
  - decorator=4.3.2
  - ipykernel=5.1.0
  - ipython=7.3.0
  - ipython_genutils=0.2.0
  - jedi=0.13.3
  - jupyter_client=5.2.4
  - jupyter_core=4.4.0
  - libsodium=1.0.16
  - openssl=1.1.1b
  - parso=0.3.4
  - pexpect=4.6.0
  - pickleshare=0.7.5
  - pip=19.0.1
  - prompt_toolkit=2.0.9
  - pygments=2.3.1
  - python=3.7.2
  - python-dateutil=2.8.0
  - pyzmq=18.0.0
  - setuptools=40.8.0
  - six=1.12.0
  - sqlite=3.26.0
  - tornado=5.1.1
  - traitlets=4.3.2
  - wcwidth=0.1.7
  - wheel=0.32.3
  - zeromq=4.3.1
  - pip:
    - spacy==2.0.18
    - aniso8601==4.1.0
    - astroid==2.1.0
    - atomicwrites==1.3.0
    - attrs==18.2.0
    - cachecontrol==0.12.5
    - cachetools==3.1.0
    - chardet==3.0.4
    - click==7.0
    - cltk==0.1.105
    - cymem==2.0.2
    - cytoolz==0.9.0.1
    - dill==0.2.9
    - firebase-admin==2.16.0
    - flask==1.0.2
    - flask-marshmallow==0.10.0
    - flask-restful==0.3.7
    - flask-sqlalchemy==2.3.2
    - flask-wtf==0.14.2
    - gitdb2==2.0.5
    - gitpython==2.1.11
    - google-api-core==1.8.0
    - google-auth==1.6.3
    - google-cloud-core==0.29.1
    - google-cloud-firestore==0.31.0
    - google-cloud-storage==1.14.0
    - google-resumable-media==0.3.2
    - googleapis-common-protos==1.5.8
    - grpcio==1.19.0
    - idna==2.8
    - itsdangerous==1.1.0
    - jinja2==2.10
    - markupsafe==1.1.1
    - marshmallow==2.19.0
    - marshmallow-sqlalchemy==0.16.1
    - mccabe==0.6.1
    - more-itertools==6.0.0
    - msgpack==0.5.6
    - msgpack-numpy==0.4.3.2
    - murmurhash==1.0.2
    - nltk==3.4
    - numpy==1.16.2
    - plac==0.9.6
    - pluggy==0.9.0
    - preshed==2.0.1
    - protobuf==3.7.0
    - psycopg2==2.7.7
    - pyasn1==0.4.5
    - pyasn1-modules==0.2.4
    - pylint==2.2.2
    - pytest==4.3.0
    - python-crfsuite==0.9.6
    - pytz==2018.9
    - pyuca==1.2
    - pyyaml==5.1
    - regex==2018.1.10
    - requests==2.21.0
    - rsa==4.0
    - scikit-learn==0.20.3
    - scipy==1.2.1
    - singledispatch==3.4.0.3
    - sklearn==0.0
    - smmap2==2.0.5
    - spacy==2.0.18
    - sqlalchemy==1.3.0b2
    - textblob==0.15.3
    - thinc==6.12.1
    - toolz==0.9.0
    - tqdm==4.31.1
    - ujson==1.35
    - urllib3==1.24.1
    - werkzeug==0.14.1
    - whoosh==2.7.4
    - wrapt==1.10.11
    - wtforms==2.2.1
